Template.umAddUser.helpers(UserManagementTemplates.umAddUserHelpers);
Template.umAddUser.events(UserManagementTemplates.umAddUserEvents);
Template.umAddUser.onCreated(UserManagementTemplates.umAddUserRendered);